import type { Vocabulary } from '../../../shared/types/index';

export const defaultVocabulary: Vocabulary = {
  en: {
    by: ['by'],
    top: ['top', 'best', 'highest'],
    bottom: ['bottom', 'worst', 'lowest'],
    most: ['most', 'highest', 'largest', 'biggest', 'best'],
    least: ['least', 'lowest', 'smallest', 'worst'],
    count: ['count', 'number of', 'how many'],
    overTime: ['over time', 'trend'],
    filters: ['in', 'for', 'where', 'with'],
    and: ['and'],
    prepositions: ['of', 'for', 'in'],
    listAction: ['which', 'what', 'list', 'show'],
    subjectQuestion: ['which', 'what'],
    ownershipVerb: ['has'],
    article: ['the'],
    listAvailability: ['do i have', 'are there', 'exist', 'available'],
    listKind: ['kind', 'kinds', 'type', 'types'],
    listCategory: ['category', 'categories'],
    listSubcategory: ['subcategory', 'sub category', 'sub categories'],
    latestYear: ['latest year', 'last year'],
    latestMonth: ['latest month', 'last month'],
    thisYear: ['this year'],
    thisMonth: ['this month'],
    dateCue: [
      'today',
      'yesterday',
      'tomorrow',
      'last',
      'this',
      'next',
      'year',
      'month',
      'week',
      'quarter',
      'day',
    ],
    yearCue: ['year'],
    monthCue: ['month'],
    dayCue: ['day', 'today', 'yesterday', 'tomorrow'],
    dayGrain: ['day', 'daily'],
    monthGrain: ['month', 'monthly'],
    yearGrain: ['year', 'yearly', 'annual'],
    yearOverYear: ['year over year', 'yoy', 'year on year'],
    comparison: ['compare', 'versus', 'vs'],
    change: ['change', 'changed', 'delta', 'growth'],
    share: ['share', 'percent', 'percentage', 'proportion'],
    unsupportedMetric: ['profit', 'margin', 'earnings', 'cost'],
  },
  pt: {
    by: ['por'],
    top: ['top', 'maiores', 'melhores'],
    bottom: ['menores', 'piores'],
    most: ['maior', 'maiores', 'melhor', 'melhores', 'mais'],
    least: ['menor', 'menores', 'pior', 'piores', 'menos'],
    count: ['contar', 'conte', 'quantos', 'numero de', 'número de'],
    overTime: ['ao longo do tempo', 'tendencia', 'tendência', 'evolucao', 'evolução'],
    filters: ['em', 'para', 'onde', 'com'],
    and: ['e'],
    prepositions: ['de', 'do', 'da', 'para', 'em'],
    listAction: ['quais', 'qual', 'liste', 'mostrar'],
    subjectQuestion: ['quais', 'qual'],
    ownershipVerb: ['tem', 'possui'],
    article: ['o', 'a'],
    listAvailability: ['tenho', 'existem', 'disponiveis', 'disponíveis'],
    listKind: ['tipo', 'tipos'],
    listCategory: ['categoria', 'categorias'],
    listSubcategory: ['subcategoria', 'subcategorias', 'sub categoria'],
    latestYear: ['ano mais recente', 'ultimo ano', 'último ano', 'ano passado', 'ano anterior'],
    latestMonth: [
      'mes mais recente',
      'mês mais recente',
      'ultimo mes',
      'último mês',
      'mes passado',
      'mês passado',
      'mes anterior',
      'mês anterior',
    ],
    thisYear: ['este ano', 'esse ano'],
    thisMonth: ['este mes', 'este mês', 'esse mes', 'esse mês'],
    dateCue: [
      'hoje',
      'ontem',
      'amanha',
      'amanhã',
      'passado',
      'passada',
      'este',
      'esta',
      'proximo',
      'próximo',
      'ano',
      'mes',
      'mês',
      'semana',
      'trimestre',
      'dia',
    ],
    yearCue: ['ano'],
    monthCue: ['mes', 'mês'],
    dayCue: ['dia', 'hoje', 'ontem', 'amanha', 'amanhã'],
    dayGrain: ['dia', 'diario', 'diária', 'diario', 'diaria'],
    monthGrain: ['mes', 'mês', 'mensal'],
    yearGrain: ['ano', 'anual'],
    yearOverYear: ['ano a ano', 'ano contra ano'],
    comparison: ['comparar', 'compare', 'versus', 'vs', 'contra'],
    change: ['mudanca', 'mudança', 'variacao', 'variação', 'crescimento'],
    share: ['participacao', 'participação', 'percentual', 'porcentagem'],
    unsupportedMetric: ['lucro', 'margem', 'custo'],
  },
};

export function buildVocabulary(configured: Vocabulary = {}): Vocabulary {
  const merged: Vocabulary = structuredClone(defaultVocabulary);
  for (const [lang, groups] of Object.entries(
    configured as Record<string, Record<string, string[]>>,
  )) {
    merged[lang] ||= {};
    for (const [group, terms] of Object.entries(groups))
      merged[lang][group] = [...new Set([...(merged[lang][group] || []), ...terms])];
  }
  return merged;
}
