services:
  moto:
    image: motoserver/moto:latest
    ports:
      - "5000:5000"
    environment:
      - MOTO_PORT=5000
      - MOTO_HOST=moto
      - MOTO_HTTP_ENDPOINT=http://moto:5000
      - MOTO_DOCKER_NETWORK_NAME=aws-mock-network
      - MOTO_DOCKER_LAMBDA_IMAGE=mlupin/docker-lambda
      - MOTO_LOG_LEVEL=debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - aws-mock-network

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=iam,s3,lambda,dynamodb,sqs,cloudwatch,logs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_HOST=localstack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - aws-mock-network

  awscli:
    image: amazon/aws-cli:latest
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - aws-mock-network

  terraform:
    image: hashicorp/terraform:latest
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - aws-mock-network

  sam-cli:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.sam-cli
    container_name: sam-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    stdin_open: true

networks:
  aws-mock-network:
    driver: bridge
