[project]
name = "sfa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.3.1",
    "google-genai>=1.20.0",
    "litellm>=1.72.6.post1",
    "python-dotenv>=1.1.0",
    "rich>=14.0.0",
]
